record_type: '0'
description: Processor Header Record
fields:
- field_number: '001'
  name: Record Identifier
  key: record_identifier
  start: 1
  end: 1
  length: 1
  format: 9(1)
  description: '"0"'
- field_number: '002'
  name: Issuer Identifier Number
  key: issuer_identifier_number
  start: 2
  end: 7
  length: 6
  format: 9(6)
- field_number: '003'
  name: Issuer Identifier Name
  key: issuer_identifier_name
  start: 8
  end: 27
  length: 20
  format: X(20)
  description: ESI Canada
- field_number: '004'
  name: Destination Name
  key: destination_name
  start: 28
  end: 47
  length: 20
  format: X(20)
  description: Carrier name
- field_number: '005'
  name: Destination Address
  key: destination_address
  start: 48
  end: 77
  length: 30
  format: X(30)
- field_number: '006'
  name: Destination City
  key: destination_city
  start: 78
  end: 92
  length: 15
  format: X(15)
- field_number: '007'
  name: Destination Province
  key: destination_province
  start: 93
  end: 94
  length: 2
  format: X(2)
- field_number: 008
  name: Destination Postal Code
  key: destination_postal_code
  start: 95
  end: 100
  length: 6
  format: X(6)
- field_number: 009
  name: Destination Telephone Number
  key: destination_telephone_number
  start: 101
  end: 110
  length: 10
  format: 9(10)
- field_number: '010'
  name: Run Date
  key: run_date
  start: 111
  end: 118
  length: 8
  format: 9(8)
  description: Date file created
- field_number: '011'
  name: Transmittal Sequence No.
  key: transmittal_sequence_no
  start: 119
  end: 121
  length: 3
  format: 9(3)
- field_number: '012'
  name: Cut-off Date
  key: cut_off_date
  start: 122
  end: 129
  length: 8
  format: 9(8)
  description: The date the latest predetermination was received
- field_number: '013'
  name: Filler
  key: filler
  start: 130
  end: 185
  length: 56
  format: X(56)
- field_number: '014'
  name: Program Version
  key: program_version
  start: 186
  end: 313
  length: 128
  format: X(128)
- field_number: '015'
  name: Filler
  key: filler_2
  start: 314
  end: 1247
  length: 934
  format: X(934)
