# Province Codes Lookup Table
# Reverse mapping: province/territory names to their codes

lookup_name: "province_codes"
description: "Canadian provinces and territories - name to code conversion"

mappings:
  "British Columbia": "BC"
  "Alberta": "AB"
  "Saskatchewan": "SK"
  "Manitoba": "MB"
  "Ontario": "ON"
  "Quebec": "PQ"
  "New Brunswick": "NB"
  "Nova Scotia": "NS"
  "Prince Edward Island": "PE"
  "Newfoundland": "NF"
  "Yukon Territory": "YT"
  "Northwest Territories": "NT"
  "Nunavut": "NU"
  "Out of Country": "OC"

