# GMS Partner Configuration for EHC Patient Record - Type "37"
partner_id: "GMS"
record_type: "37"

field_overrides:
  # Field 02 - Carrier ID
  # Override: "49"
  - key: "carrier_id"
    default_value: "49"

