# GMS Partner Configuration for Client Address Record - Type "29"
partner_id: "GMS"
record_type: "29"

field_overrides:
  # Field 02 - Carrier ID
  # Override: "49"
  - key: "carrier_id"
    default_value: "49"

