# GMS Partner Configuration for Patient Exception Record - Type "24"
partner_id: "GMS"
record_type: "24"

field_overrides:
  # Field 02 - Carrier ID
  # Override: "49"
  - key: "carrier_id"
    default_value: "49"

