# GMS Partner Configuration for Patient Accumulator Record - Type "23"
partner_id: "GMS"
record_type: "23"

field_overrides:
  # Field 02 - Carrier ID
  # Override: "49"
  - key: "carrier_id"
    default_value: "49"

