record_type: '8'
description: File Batch Control Record
fields:
- field_number: '001'
  name: Record Type
  key: record_type
  start: 1
  end: 1
  length: 1
  format: 9(1)
  description: '"8"'
- field_number: '002'
  name: Issuer Identifier Number
  key: issuer_identifier_number
  start: 2
  end: 7
  length: 6
  format: 9(6)
  description: Defaults to “610068”
- field_number: '003'
  name: Record Count
  key: record_count
  start: 8
  end: 15
  length: 8
  format: 9(8)
  description: 'Number of records on file including Headers and Trailers (or: All
    records for a client including Headers and Trailers)'
- field_number: '004'
  name: Grand Total
  key: grand_total
  start: 16
  end: 25
  length: 10
  format: 9(8)V99
  description: Total value of claims paid on the file
  value_format:
    type: implied_decimal
    scale: 2
- field_number: '005'
  name: Filler
  key: filler
  start: 25
  end: 750
  length: 726
  format: X(726)
