record_type: '8'
description: File Batch Control Record
fields:
- field_number: '001'
  name: Record Identifier
  key: record_identifier
  start: 1
  end: 1
  length: 1
  format: 9(1)
  description: '"8"'
- field_number: '002'
  name: Issuer Identifier Number
  key: issuer_identifier_number
  start: 2
  end: 7
  length: 6
  format: 9(6)
  description: null
- field_number: '003'
  name: Record Count
  key: record_count
  start: 8
  end: 15
  length: 8
  format: 9(8)
  description: Number of records on file including Headers and Trailers
- field_number: '004'
  name: Filler
  key: filler
  start: 16
  end: 79
  length: 64
  format: X(64)
  description: null
- field_number: '005'
  name: Claim Amount
  key: claim_amount
  start: 80
  end: 89
  length: 10
  format: 9(10,2)
  description: Total value of the positive claims for this dataset (type 4)
  value_format:
    type: implied_decimal
    scale: 2
- field_number: '006'
  name: Reversal Amount
  key: reversal_amount
  start: 90
  end: 99
  length: 10
  format: 9(10,2)
  description: Total value of the reversed claims for this dataset (type 5)
  value_format:
    type: implied_decimal
    scale: 2
- field_number: '007'
  name: Adjustment Amount
  key: adjustment_amount
  start: 100
  end: 110
  length: 11
  format: s9(10,2)
  description: Total value of the adjustment amounts on claims for this dataset for
    type 4 records
  value_format:
    type: implied_decimal
    scale: 2
- field_number: 008
  name: Total Amount Payable
  key: total_amount_payable
  start: 111
  end: 123
  length: 13
  format: s9(12,2)
  description: Calculated total amount payable for this dataset (Claim Amount - Reversal
    Amount + Adjustment Amount)
  value_format:
    type: implied_decimal
    scale: 2
- field_number: 009
  name: Filler
  key: filler_2
  start: 124
  end: 4561
  length: 4438
  format: X(4438)
  description: null
